// Single place every icon comes from. Swap sets with ICON_SET in ./config.js -
// callers import the same names either way, so nothing else has to change.
import { ICON_SET } from "./config.js";
import * as lucide from "./lucide-set.js";
import * as phosphor from "./phosphor-set.js";

const active = ICON_SET === "phosphor" ? phosphor : lucide;

export const Activity = active.Activity;
export const AlertCircle = active.AlertCircle;
export const AlertTriangle = active.AlertTriangle;
export const ArrowRightLeft = active.ArrowRightLeft;
export const Award = active.Award;
export const BarChart2 = active.BarChart2;
export const BarChart3 = active.BarChart3;
export const Briefcase = active.Briefcase;
export const Calendar = active.Calendar;
export const CalendarCheck = active.CalendarCheck;
export const Check = active.Check;
export const CheckCircle = active.CheckCircle;
export const CheckCircle2 = active.CheckCircle2;
export const ChevronDown = active.ChevronDown;
export const ChevronLeft = active.ChevronLeft;
export const ChevronRight = active.ChevronRight;
export const Clipboard = active.Clipboard;
export const Clock = active.Clock;
export const Coffee = active.Coffee;
export const Copy = active.Copy;
export const Database = active.Database;
export const Download = active.Download;
export const ExternalLink = active.ExternalLink;
export const Eye = active.Eye;
export const EyeOff = active.EyeOff;
export const FileText = active.FileText;
export const Filter = active.Filter;
export const GitCompare = active.GitCompare;
export const Github = active.Github;
export const Globe = active.Globe;
export const GripVertical = active.GripVertical;
export const Hash = active.Hash;
export const Heading = active.Heading;
export const Heart = active.Heart;
export const Inbox = active.Inbox;
export const Info = active.Info;
export const KanbanSquare = active.KanbanSquare;
export const Layers3 = active.Layers3;
export const LayoutGrid = active.LayoutGrid;
export const Link2 = active.Link2;
export const List = active.List;
export const ListOrdered = active.ListOrdered;
export const ListTodo = active.ListTodo;
export const Lock = active.Lock;
export const LogIn = active.LogIn;
export const Mail = active.Mail;
export const MessageSquare = active.MessageSquare;
export const Minus = active.Minus;
export const Moon = active.Moon;
export const Move = active.Move;
export const Palette = active.Palette;
export const Paperclip = active.Paperclip;
export const Pause = active.Pause;
export const Pencil = active.Pencil;
export const PieChart = active.PieChart;
export const Play = active.Play;
export const Plug = active.Plug;
export const Plus = active.Plus;
export const RotateCcw = active.RotateCcw;
export const Settings = active.Settings;
export const SlidersHorizontal = active.SlidersHorizontal;
export const Square = active.Square;
export const Sun = active.Sun;
export const Tag = active.Tag;
export const Target = active.Target;
export const Timer = active.Timer;
export const Trash2 = active.Trash2;
export const TrendingDown = active.TrendingDown;
export const TrendingUp = active.TrendingUp;
export const Type = active.Type;
export const Undo2 = active.Undo2;
export const Upload = active.Upload;
export const User = active.User;
export const UserCheck = active.UserCheck;
export const UserPlus = active.UserPlus;
export const Users = active.Users;
export const Users2 = active.Users2;
export const Workflow = active.Workflow;
export const Wrench = active.Wrench;
export const X = active.X;
